-- Mutable application data only. The legacy csci467.parts table remains in
-- MySQL, is read-only, and intentionally has no cross-database foreign keys.

CREATE TABLE IF NOT EXISTS inventory (
  part_number INTEGER PRIMARY KEY,
  quantity_on_hand INTEGER NOT NULL DEFAULT 0 CHECK (quantity_on_hand >= 0),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS shipping_rates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  min_weight NUMERIC(12,4) NOT NULL UNIQUE CHECK (min_weight >= 0),
  max_weight NUMERIC(12,4) NULL,
  charge NUMERIC(12,2) NOT NULL CHECK (charge >= 0),
  CONSTRAINT chk_shipping_range CHECK (max_weight IS NULL OR max_weight > min_weight)
);

CREATE TABLE IF NOT EXISTS orders (
  id UUID PRIMARY KEY,
  order_number BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  idempotency_key VARCHAR(128) NOT NULL UNIQUE,
  status VARCHAR(30) NOT NULL CHECK (status IN ('PENDING_PAYMENT', 'AUTHORIZED', 'PAYMENT_FAILED', 'SHIPPED')),
  customer_name VARCHAR(120) NOT NULL,
  customer_email VARCHAR(254) NOT NULL,
  address_line1 VARCHAR(150) NOT NULL,
  address_line2 VARCHAR(150) NULL,
  city VARCHAR(100) NOT NULL,
  state_region VARCHAR(100) NOT NULL,
  postal_code VARCHAR(20) NOT NULL,
  country VARCHAR(100) NOT NULL,
  subtotal NUMERIC(12,2) NOT NULL CHECK (subtotal >= 0),
  shipping_charge NUMERIC(12,2) NOT NULL CHECK (shipping_charge >= 0),
  total_amount NUMERIC(12,2) NOT NULL CHECK (total_amount >= 0),
  total_weight NUMERIC(12,4) NOT NULL CHECK (total_weight >= 0),
  payment_transaction_id VARCHAR(64) NOT NULL UNIQUE,
  payment_authorization_number VARCHAR(255) NULL,
  card_last4 CHAR(4) NULL,
  carrier VARCHAR(255) NULL,
  tracking_number VARCHAR(100) NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  authorized_at TIMESTAMPTZ NULL,
  shipped_at TIMESTAMPTZ NULL
);

CREATE INDEX IF NOT EXISTS idx_orders_created_at ON orders (created_at);
CREATE INDEX IF NOT EXISTS idx_orders_status_created ON orders (status, created_at);
CREATE INDEX IF NOT EXISTS idx_orders_total_amount ON orders (total_amount);
CREATE INDEX IF NOT EXISTS idx_orders_customer_email ON orders (customer_email);

CREATE TABLE IF NOT EXISTS order_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id UUID NOT NULL REFERENCES orders(id),
  part_number INTEGER NOT NULL,
  description VARCHAR(50) NOT NULL,
  unit_price NUMERIC(12,2) NOT NULL CHECK (unit_price >= 0),
  unit_weight NUMERIC(12,4) NOT NULL CHECK (unit_weight >= 0),
  quantity INTEGER NOT NULL CHECK (quantity > 0),
  line_total NUMERIC(12,2) NOT NULL CHECK (line_total >= 0)
);

CREATE INDEX IF NOT EXISTS idx_order_items_order ON order_items (order_id);

CREATE TABLE IF NOT EXISTS order_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id UUID NOT NULL REFERENCES orders(id),
  status VARCHAR(30) NOT NULL,
  note VARCHAR(500) NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_order_events_order ON order_events (order_id, id);

CREATE TABLE IF NOT EXISTS inventory_movements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  part_number INTEGER NOT NULL,
  quantity_delta INTEGER NOT NULL,
  reason VARCHAR(30) NOT NULL CHECK (reason IN ('RECEIVED', 'ORDER_RESERVED', 'PAYMENT_RELEASED')),
  order_id UUID NULL REFERENCES orders(id),
  note VARCHAR(500) NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_inventory_movements_part ON inventory_movements (part_number, id);
CREATE INDEX IF NOT EXISTS idx_inventory_movements_order ON inventory_movements (order_id);
